### ISSUE TITLE
帮忙看看哪里问题

### ISSUE THREAD

**Issue by LimitBreaker01** [AmbitiousJun/go-emby2alist#61]
<img width="944" alt="Image" src="https://github.com/user-attachments/assets/15fcf3e8-c0c3-4ab5-8d5f-1b672b73f890" />
<img width="1087" alt="Image" src="https://github.com/user-attachments/assets/ce1c17b5-2eb9-4d97-a9ca-6c138a39d351" />
<img width="907" alt="Image" src="https://github.com/user-attachments/assets/a7b24de9-8249-4ede-9472-66148e0a7eb3" />
<img width="827" alt="Image" src="https://github.com/user-attachments/assets/d9842b7c-bd60-47ef-a1e2-336ebe929f53" />
<img width="1005" alt="Image" src="https://github.com/user-attachments/assets/5008c11d-e487-4aab-a4e0-1b817cf2332a" />

1.没有安装emby服务容器
2.安装了docker
3.alist脚本启动并且挂载上了阿里盘
4.没有将阿里盘文件挂载到vps磁盘里

**Comment by AmbitiousJun** [comment]
你的 emby 是部署在宿主机的 8096 端口上，而本项目服务是部署在 docker 的内网环境，无法直接通过 127.0.0.1 访问到宿主机的服务

可以试一下这两种方法：

1. 修改一下 `go-emby2alist` 的 `docker-compose.yml` 配置，使用 host 模式运行，原配置无需改动：

```yaml
version: "3.1"
services:
  go-emby2alist:
    image: ambitiousjun/go-emby2alist:v1.5.2
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-emby2alist
    volumes:
      - ./config.yml:/app/config.yml
      - ./ssl:/app/ssl
    network_mode: "host"
```

2. 给 `go-emby2alist` 指定一个宿主机网关域名，让容器内部能够访问到宿主机的 8096 端口服务：

`docker-compose.yml` 文件修改如下：

```yaml
version: "3.1"
services:
  go-emby2alist:
    image: ambitiousjun/go-emby2alist:v1.5.2
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-emby2alist
    volumes:
      - ./config.yml:/app/config.yml
      - ./ssl:/app/ssl
    ports:
      - 8095:8095 # http
      - 8094:8094 # https
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

`config.yml` 修改一下 emby 的访问地址：

```yaml
emby:
  host: http://host.docker.internal:8096            # emby 访问地址
```
